version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: 'strangepassvord'
    volumes:
      - './redis:/data:rw'
      - './redis.conf:/etc/redis.conf'
    ports:
      - '6379:6379'