services:
  nginx-test:
    image: nginx:1.23.3-alpine
    ports:
      - 443:443/tcp
      - 443:443/udp
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ../letsencrypt/cert/archive:/cert
      - ./test:/code
      - ./test:/etc/nginx/html
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - net
  php-83-fpm:
    image: wacdis/php-fpm:8.3
    volumes:
      - ./test:/code
    networks:
      - net
    ports:
      - 9000
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: jSRhdHf6lksjdf3NASDkseokrnetworks
networks:
  net:
    name: net