version: "3"
services:
  certbot-nginx:
    image: wacdis/nginx-quic:latest
    volumes:
      - ./cert:/etc/letsencrypt/archive
      - ./www:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      certbot-core:
    ports:
      - "80:80"
  certbot-certbot:
    image: certbot/certbot
    networks:
      certbot-core:
    volumes:
      - ./cert:/etc/letsencrypt/archive
      - ./www:/var/www/html/
    command: certonly --webroot -w /var/www/html/ -n --agree-tos -m hostmaster@wacdis.com -d dev.wacdis.com
    # command: certonly --webroot -w /var/www/html/ -n --agree-tos --renew-by-default -m hostmaster@wacdis.com -d dev.wacdis.com
networks:
  certbot-core:
