version: "3"
services:
  gulp:
    image: alpine
    container_name: gulp-sync
    volumes:
      - ./html:/project/html
    environment:
      - REMOTE_SERVER_URL=https://wacdis.com/html
    command: ["tail", "-f", "/dev/null"]