version: "3"
services:
  ######
  test-www:
    image: wacdis/nginx-quic:beta
    container_name: test-www
    volumes:
      - ./www:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      net:
    ports:
      - "80:80"
      - "443:443"
networks:
  net:
    name: net 